/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UI.Dictionary;
import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import java.text.ParseException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author quocn
 */
public class MultimediaDatabaseSupportTool extends javax.swing.JFrame {

    /**
     * Creates new form MultimediaDatabaseSupportTool
     */
    public static int lang = 1;
    public MultimediaDatabaseSupportTool() {
        initComponents();
        myInit();
        setComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboBoxLang = new javax.swing.JComboBox<>();
        labelTD = new javax.swing.JLabel();
        labelMDS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("MULTIMEDIA DATABASE SUPPORT TOOL");

        comboBoxLang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Tiếng việt" }));
        comboBoxLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLangActionPerformed(evt);
            }
        });

        labelTD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTD.setText("Text Database");
        labelTD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTDMouseClicked(evt);
            }
        });

        labelMDS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelMDS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMDS.setText("Multimedia data structure");
        labelMDS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMDSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(comboBoxLang, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMDS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(comboBoxLang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMDS, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLangActionPerformed
        // TODO add your handling code here:
        if(comboBoxLang.getSelectedIndex() == 0) lang = 1;
        else lang = 2;
        changLang();
    }//GEN-LAST:event_comboBoxLangActionPerformed

    private void labelMDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMDSMouseClicked
        // TODO add your handling code here:
        new UI.MultiDimensionalDataStructureUI().setVisible(true);
    }//GEN-LAST:event_labelMDSMouseClicked

    private void labelTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTDMouseClicked
        // TODO add your handling code here:
        new UI.TextDatabase().setVisible(true);
    }//GEN-LAST:event_labelTDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
        } catch (ParseException | UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultimediaDatabaseSupportTool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> comboBoxLang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMDS;
    private javax.swing.JLabel labelTD;
    private javax.swing.JLabel labelTitle;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        loadLangComboBox();
    }

    private void loadLangComboBox() {
        
    }

    private void changLang() {
        loadData();
    }

    private void loadData() {
        loadTitle();
        loadLableMDS();
        loadLabelTD();
    }

    private void loadTitle() {
        labelTitle.setText(Dictionary.Words.TITLE.getString());
    }

    private void loadLableMDS() {
        labelMDS.setText(Dictionary.Words.MULTI_DIMENSIONAL_DATA_STRUCTURE.getString());
    }

    private void loadLabelTD() {
        labelTD.setText(Dictionary.Words.TEXT_DATABASE.getString());
    }

    public static void setComboBox() {
        if(lang == 1){
            comboBoxLang.setSelectedIndex(0);
        }else{
            comboBoxLang.setSelectedIndex(1);
        }
    }
}
