/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latentsemanticindexing.control;

import Data.Data;
import UI.Dictionary;
import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quocn
 */
public class DocumentsManagement extends javax.swing.JFrame {

    /**
     * Creates new form DocumentsManagement
     */
    
    private static DocumentsManagement instance = null;
    
    public DocumentsManagement() throws Exception {
        initComponents();
        loadCollecionNames();
        loadCollectionData();
        StopWords.createStopWords();
        setLang();
    }
    
    public void loadCollecionNames() throws Exception{
        
        comboBoxCollection.removeAllItems();
        
        String sql = "select name_collection from information";
        
        ResultSet res = Data.getResultsetQuery(sql, "lsi");
        while(res.next()){
            comboBoxCollection.addItem(res.getString(1));
        }
        comboBoxCollection.addItem(Dictionary.Words.ADD.getString() + "...");
    }
    
    public static DocumentsManagement getInstance() throws Exception{
        if(instance == null) instance = new DocumentsManagement();
        instance.setLang();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitile = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        tabManagement = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDocuments = new javax.swing.JTable();
        tabAdd = new javax.swing.JPanel();
        textName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaText = new javax.swing.JTextArea();
        buttonDone = new javax.swing.JButton();
        textConfirm = new javax.swing.JLabel();
        labelChooseCollection = new javax.swing.JLabel();
        comboBoxCollection = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labelTitile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitile.setText("COLLECTION MANAGEMENT");

        tableDocuments.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableDocuments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Text"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDocuments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableDocumentsMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableDocuments);
        if (tableDocuments.getColumnModel().getColumnCount() > 0) {
            tableDocuments.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout tabManagementLayout = new javax.swing.GroupLayout(tabManagement);
        tabManagement.setLayout(tabManagementLayout);
        tabManagementLayout.setHorizontalGroup(
            tabManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        tabManagementLayout.setVerticalGroup(
            tabManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabManagementLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("Documents management", tabManagement);

        textName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name Document:");

        textAreaText.setColumns(20);
        textAreaText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAreaText.setRows(5);
        jScrollPane1.setViewportView(textAreaText);

        buttonDone.setText("DONE");
        buttonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoneActionPerformed(evt);
            }
        });

        textConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout tabAddLayout = new javax.swing.GroupLayout(tabAdd);
        tabAdd.setLayout(tabAddLayout);
        tabAddLayout.setHorizontalGroup(
            tabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAddLayout.createSequentialGroup()
                        .addComponent(textConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDone))
                    .addGroup(tabAddLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textName))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabAddLayout.setVerticalGroup(
            tabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonDone)
                    .addComponent(textConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tab.addTab("Add new document", tabAdd);

        labelChooseCollection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelChooseCollection.setText("Choose collection:");

        comboBoxCollection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCollectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitile, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tab)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelChooseCollection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCollection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChooseCollection)
                    .addComponent(comboBoxCollection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDocument(String name, String text) throws Exception{
        boolean confirm = true;
        try{
            
            
            if(name.isEmpty() || text.isEmpty()){
                textConfirm.setText("Khong duoc bo trong");
                throw new Exception();
            }

            String sql = "INSERT INTO documents VALUES (null, '" 
                        + name + "', '" + text + "');";
            String collectionName = (String) comboBoxCollection.getSelectedItem();
            String databaseName = getDatabaseName(collectionName);
            Data.setResultsetUpdate(sql, databaseName );
        }catch(Exception ex){
            ex.printStackTrace();
            confirm = false;
            
        }finally{
            if(confirm){
                textConfirm.setForeground(Dictionary.COLOR.SUCCESSFUL.getColor());
                textConfirm.setText(Dictionary.Words.INSERT.getString() + " "
                        +Dictionary.Words.SUCCESSFUL.getString());

                clearComponent();
            }else{
                Toolkit.getDefaultToolkit().beep();
                textConfirm.setForeground(Dictionary.COLOR.FAIL.getColor());
                textConfirm.setText(Dictionary.Words.INSERT.getString() + " " 
                        +Dictionary.Words.FAIL.getString());
            }
        }
    }
    
    private String getDatabaseName(String collectionName){
        String sql = "select name_database from information where name_collection = '"
                + collectionName + "'";
        try{
            ResultSet res =  Data.getResultsetQuery(sql, "lsi");
            res.next();
            return res.getString(1);
        }catch(Exception ex){
            //ex.printStackTrace();
        }
        return null;
    }
    
    private void addTermWord(String name, String text) throws Exception{
        Vector listTermWord = RemoveStopWord.getList(text);
        HashMap map = new HashMap<String, Integer>();
        for(int i=0; i<listTermWord.size(); ++i){
            String word = (String) listTermWord.get(i);
            try {            
                checkWord(word);
            } catch (SQLException ex) {
                //ex.printStackTrace();
            }
           // System.out.println(word + "------");
            if(map.containsKey(word)){
             //   System.out.println(word +" = " + map.get(word));
                map.put(word, (int) map.get(word) + 1 );
            }else{
                map.put(word, 1);
            }
        }
        String databaseName = getDatabaseName((String) comboBoxCollection.getSelectedItem());
        for (Object e:map.keySet()){
            Integer count = (Integer) map.get(e.toString());
            String idTermWord = getIDTermWord(e.toString(), databaseName);
            String idDocument = getIDDocument(name, databaseName);
            setNumber(idDocument, idTermWord , count, databaseName);
        }
    }
    
    private String getIDTermWord(String wordString, String databaseName) throws Exception{
        String sql = "select id from terms where word = '" + wordString + "'";
        
        ResultSet res = Data.getResultsetQuery(sql, databaseName);
        res.next();
        return res.getString(1);
    }
    
    private String getIDDocument(String nameString, String databaseName) throws Exception{
        String sql = "select id from documents where name = '" + nameString + "'";
        
        ResultSet res = Data.getResultsetQuery(sql, databaseName);
        res.next();
        return res.getString(1);
    }
    
    private String getIdTermWord(String word) throws Exception{
        String sql = "select id from terms where word = '" + word + "'";
        String databaseName = getDatabaseName((String) comboBoxCollection.getSelectedItem());
        try {
            ResultSet res = Data.getResultsetQuery(sql,databaseName );
            if(res.next()){
                return res.getString(1);
            }
            return "";
        } catch (Exception ex) {
            //ex.printStackTrace();
        }
        return "";
    }
    
    private void setNumber(String idDocument, String idTerm, Integer count, String databaseName) throws SQLException{
        String sql = "insert into term_document(id_term, id_document, count) value ('"
                + idTerm + "','" + idDocument + "','" + count + "')";
        
        Data.setResultsetUpdate(sql, databaseName);
    }
    
    private void checkWord(String word) throws SQLException{
        String sql = "select top 1 word from terms";
        ResultSet res;
        try {
            res = Data.getResultsetQuery(sql, comboBoxCollection.getSelectedItem().toString());
            if(res.next()){
                return;
            }
        } catch (Exception ex) {
            sql = "INSERT INTO terms VALUES (null, '" + word + "')";
            Data.setResultsetUpdate(sql, comboBoxCollection.getSelectedItem().toString());
            //ex.printStackTrace();
        }
        
    }
    
    private void comboBoxCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCollectionActionPerformed
        // TODO add your handling code here:
        if(comboBoxCollection.getSelectedIndex() == comboBoxCollection.getItemCount() - 1 
                && comboBoxCollection.getSelectedIndex() > 0){
                AddNewCollection.getIntance(comboBoxCollection).setVisible(true);
        }
        loadCollectionData();
    }//GEN-LAST:event_comboBoxCollectionActionPerformed

    private void buttonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoneActionPerformed
        try {
            String name = textName.getText();
            String text = textAreaText.getText();
            addDocument(name, text);
            addTermWord(name, text);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonDoneActionPerformed

    private void tableDocumentsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDocumentsMouseReleased
        // TODO add your handling code here:
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem itemXoa = new JMenuItem(Dictionary.Words.DELETE.getString());

        popupMenu.add(itemXoa);

        itemXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable ) {
            popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableDocumentsMouseReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
        } catch (ParseException | UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DocumentsManagement().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DocumentsManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDone;
    private javax.swing.JComboBox<String> comboBoxCollection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelChooseCollection;
    private javax.swing.JLabel labelTitile;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JPanel tabAdd;
    private javax.swing.JPanel tabManagement;
    private javax.swing.JTable tableDocuments;
    private javax.swing.JTextArea textAreaText;
    private javax.swing.JLabel textConfirm;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables

    private void clearComponent() {
        textAreaText.setText("");
        textName.setText("");
    }

    private void loadCollectionData() {
        String sql = "select name, text from documents";
        String databaseName = getDatabaseName(comboBoxCollection.getSelectedItem().toString());
        DefaultTableModel model = (DefaultTableModel) tableDocuments.getModel();
        model.getDataVector().removeAllElements();
        try {
            ResultSet res = Data.getResultsetQuery(sql, databaseName);
            while(res.next()){
                Vector vector = new Vector();
                vector.add(res.getString(1));
                vector.add(res.getString(2));
                model.addRow(vector);
            }
            tableDocuments.revalidate();
        } catch (Exception ex) {
                //ex.printStackTrace();
                model.getDataVector().removeAllElements();
                tableDocuments.revalidate();
        }
    }

    private void setLang() {
        this.setTitle(Dictionary.Words.COLLECTION_MANAGEMENT.getString());
        this.labelTitile.setText(Dictionary.Words.COLLECTION_MANAGEMENT_TITLE.getString());
        this.labelChooseCollection.setText(Dictionary.Words.CHOOSE_COLLECTION.getString());
        this.tab.setTitleAt(0, Dictionary.Words.DOCUMENT_MANAGEMENT.getString());
        this.tab.setTitleAt(1, Dictionary.Words.ADD_NEW_DOCUMENT.getString());
        loadCollectionData();
    }
    
    public void changLang(){
        setLang();
    }
}
